name: marinamoda
description: 'The music industry has undergone significant transformations in recent years, thanks to the advent of technology and the digital age. Streaming services have become the primary mode of music consumption, with giants like Spotify, Apple Music, and Amazon Music dominating the market. While these platforms offer convenience and access to a vast library of music, they come with their fair share of challenges, including centralized control, unfair artist compensation, and data privacy concerns. In response to these issues, a groundbreaking solution has emerged: Marina.Moda, a decentralized music streaming service powered by artificial intelligence (AI).'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0 
  firebase_messaging:  ^14.6.3
  flutter_local_notifications: ^16.2.0
  firebase_dynamic_links: ^5.3.3
  firebase_in_app_messaging: ^0.7.3+3
  #to create webview  
  flutter_inappwebview: ^5.7.2+3
  #to get theme modes set by user
  shared_preferences: ^2.1.2
  # lottie icons
  lottie: ^2.4.0
  # for network connectivity
  connectivity_plus: ^4.0.1
  #draw svg icons
  flutter_svg: #^1.1.0
  # state management
  provider: ^6.0.5
  # Google Mobile Ads 
  google_mobile_ads: ^4.0.0 
  # share content from  Flutter app
  share_plus: ^7.0.2
  # launch web URLs
  url_launcher: ^6.1.11
  # for handling permissions for downloading tasks
  permission_handler: ^10.3.0
  path_provider: ^2.0.15
  # to download files
  dio: ^5.2.1+1
  in_app_review: ^2.0.6
  device_info_plus: ^9.0.2
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: SegUI
      fonts:
        - asset: assets/fonts/segoeui.ttf
        - asset: assets/fonts/seguisb.ttf
          weight: 900